name: Entrenar y Guardar Modelo

on:
  schedule:
    - cron: "0 0 1 * *"  
  push:
    paths:
      - 'data/creditcard_sample.csv' 
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

   
      - name: Install dependencies
        run: pip install -r requirements.txt

    
      - name: Train model
        run: python train.py

     
      - name: Commit and Push Model
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add fraud_model.pkl
          git commit -m "Actualizar modelo"
          git push
